#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config bottom_padding 0

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config paddingless_monocle true
bspc config single_monocle false

bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a Conky state=floating
bspc rule -a stalonetray state=floating
bspc rule -a Lxappearance state=floating

$HOME/.config/cat-configs/bin/system/autostart