#!/bin/sh

# Autostart

## Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Autokill
killall -9 ksuperkey xfce4-power-manager &
killall sxhkd; sxhkd &
killall dunst; dunst &

## Power Manager
xfce4-power-manager &

## Compositor
picom -b &

## Background
feh --bg-fill -r -z $HOME/Pictures/Wallpapers &

## Redshift (Optional)
# redshift -x && redshift -O 4000k &

## Fix Cursor
xsetroot -cursor_name left_ptr &

## Bar
$HOME/.config/polybar/launch.sh &

## Super Key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Mpd
exec mpd &

# Workspaces

bspc monitor -d 1 2 3 4 5 6 7 8

# Config

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config bottom_padding 0

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config paddingless_monocle true
bspc config single_monocle false

# Rules

bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a Conky state=floating
bspc rule -a stalonetray state=floating
bspc rule -a Lxappearance state=floating
